### ISSUE TITLE
Filename in modal does not update upon opening new files

### ISSUE THREAD

**Issue by Pyxidatol-C** [Mapioi/OnlineLoggerPro#3]
Opening the first file:
![screenshot 2018-11-16 at 18 40 33](https://user-images.githubusercontent.com/13273623/48637846-2c90f680-e9cf-11e8-9ed5-be8ddbcfebf0.png)

Opening the second file, and bringing up the export modal:
![screenshot 2018-11-16 at 18 40 47](https://user-images.githubusercontent.com/13273623/48637847-2c90f680-e9cf-11e8-8d1f-74519e9e7c8d.png)

**Comment by TrakJohnson** [comment]
a 1 minute fix much wow am of impressed

**Comment by ramzialhaddadtm** [comment]
same here
